### ISSUE TITLE
Harbor UI Extension问题记录

### ISSUE THREAD

**Issue by dingluyy** [dingluyy/qa#1]
- [x] ~~1. 未配置harbor时，镜像管理和日志页面没有提示harbor未配置，展示的是列表页。日志页面没展示title。~~
验证通过。
![](https://github.com/user-attachments/assets/a6dbc872-c019-4a9d-b829-777f1959d7a7)
![](https://github.com/user-attachments/assets/97b398d9-6685-445e-a8dc-a09e90660152)

- [x] ~~2. 删除harbor配置，需要把用户名密码一同删掉，并且不显示报错信息。~~
验证通过。harbor配置删除成功，返回配置harbor页面，用户名密码清空。
![](https://github.com/user-attachments/assets/476be918-0e84-4700-8f8d-810cdbda12d4)

- [x] ~~3. 未配置harbor时，不展示delete和cancel按钮，reset按钮展示.~~
验证通过。未配置harbor时，不展示delete按钮，reset按钮用cancel按钮代替。
![](https://github.com/user-attachments/assets/6d04f508-bddc-438f-ac45-a5d4a6c378be)

- [x] 4. 创建harbor配置时，点击取消按钮，用户名和密码未清空
验证通过。
- [x] 5. 修改密码，输入错误的当前使用密码，错误提示展示null
验证通过。显示harbor接口返回信息。

- [x] 6. 翻译：删除Harbor配置时，确认提示展示的是HarborConfig，其他页面展示的是Harbor配置
验证通过。翻译正确。

- [x] 7. 创建标签，同名时提示错误信息 -- 优化
![](https://github.com/user-attachments/assets/c24d8025-5378-467d-9dfb-91d298b158bc)
- [x] 8. 创建标签，名称超长时提示错误信息 -- 优化
![](https://github.com/user-attachments/assets/2c31ecb4-6b81-4d5e-acf1-79bc2c530478)
- [x] 9. 删除标签时，标签名字过长，删除提示标签名称超出弹窗范围；中文翻译，Label可以翻译成标签
![](https://github.com/user-attachments/assets/65604224-7707-4bf7-afdf-ef72023ef79a)
- [x] 10. 选择多个标签，删除，控制台报错
![](https://github.com/user-attachments/assets/80e778cd-2a5c-4d2a-b25d-bd4cf1253cb3)
- [x] 11.  标签列表页，只展示10条数据，无法跳转第二页
![](https://github.com/user-attachments/assets/da44a76f-4d98-490f-a3ca-65aec86e8beb)

**Comment by dingluyy** [comment]
镜像管理
---
- [x] 12. 新建项目，存储容量与Harbor里默认单位和单位表示不一致，Harbor里默认为GiB
验证通过。存储容量与harbor展示一致。
- [x] 13. 不输入项目名称/超长名称，错误提示 中文翻译下提示英文；目前有两个提示，框内红色字体提示，右上角黄色提示框
验证通过。没有右上角黄色提示框，不输入项目名称提示名称不能为空，超长名称提示信息展示harbor接口返回信息。
- [x] 14. 项目名称输入特殊字符提示，中文翻译下提示内容是中文，同13存在两个提示的问题
验证通过。提示信息“项目名称由小写字符、数字、和._-组成，且至少有两个字符并以字母或数字开头”，没有右上角黄色提示框。
- [x] 15. 项目重名提示，中文翻译下提示内容是中文，同13存在两个提示的问题
验证通过。提示信息展示harbor接口返回信息，没有右上角黄色提示。
- [x] 16. 保存项目，提示错误信息，取消。不刷新页面，新建项目，展示上一次的错误信息
验证通过。点击取消，新建项目，没有错误信息。
- [x] 17.  删除项目时，项目名字过长，删除提示项目名称超出弹窗范围；中文翻译，Image Management可以翻译
验证通过。超长名称折行展示，翻译正确。
- [x] 18. 点击项目名称进入项目详情页，项目名称过长展示问题 -- 目前是滑动
验证通过。超长名称截断展示。

Image Store: 点击项目仓库名称 --> 镜像仓库
---
- [x] 19. 删除时，Image Store是否翻译
![](https://github.com/user-attachments/assets/13ed8014-2637-4208-b7c1-e108eedbada6)

Artifacts: 点击项目仓库名称 --> 镜像仓库列表 --> 点击镜像名称
---
- [x] ~~20. 删除Artifacts，Artifacts是否翻译~~
不用修改。
![](https://github.com/user-attachments/assets/4820cb03-9bf5-4181-afb6-f8019b0ccfd8)
- [x] 21. 点击右侧按钮，点击添加标签，存在超长标签名称时超出弹窗
![](https://github.com/user-attachments/assets/403d6218-cfea-4953-b557-ce568b269881)
- [x] 22. 镜像仓库跳转链接不对，之前版本是跳转到当前项目的镜像仓库列表页，现在是跳转到镜像管理列表页面
![](https://github.com/user-attachments/assets/339db91c-6b3d-485c-8305-5883869513a6)


点击项目仓库名称 --> 标签
---
- [x] 23. 新建标签，标签重名错误提示，目前展示带错误code
![](https://github.com/user-attachments/assets/3919887b-9d5a-4d74-8784-01e03f1001e8)
- [x] 24. 创建标签，名称超长时提示错误信息 -- 优化
![](https://github.com/user-attachments/assets/b9225973-8bf7-4cd6-a83f-8a30285dc366)
- [x]  25. 删除标签时，标签名字过长，删除提示标签名称超出弹窗范围；中文翻译，Label可以翻译成标签
![](https://github.com/user-attachments/assets/ddc84b04-5497-4c13-9008-09800f577cfe)
- [x]  26. 选择多个标签，删除，控制台报错
![](https://github.com/user-attachments/assets/c29ebd92-aa8b-4d98-b3f0-c4020a7a7d7f)
- [x] 27. 标签列表页，只展示10条数据，无法跳转第二页
![](https://github.com/user-attachments/assets/d53eca4b-5846-4501-9f41-a7e68d6dfa63)


点击项目仓库名称 --> 成员
---
- [x] 28. 删除成员，弹窗，member是否翻译
![](https://github.com/user-attachments/assets/02e62f2f-8bf6-4461-97a8-6c5e8c7c7362)
- [x] 管理员用户，无法添加成员
![](https://github.com/user-attachments/assets/17bcb4b4-5ed0-4f02-8f40-be1df442a2cc)

**Comment by smallteeths** [comment]
20.  删除Artifacts，Artifacts是否翻译

harbor 也没有翻译，保持现状

**Comment by dingluyy** [comment]
- [x] 30.不安全的https harbor，不勾选跳过证书验证，提示信息错误
![](https://github.com/user-attachments/assets/316f24b0-2669-4746-90e2-f6cb09d1aec9)

**Comment by dingluyy** [comment]
- [x] 31. 移除Harbor配置 / 配置Harbor时点击取消，跳过证书认证未重置
- [x] 32. 普通用户已同步harbor账号，rancher管理员账号修改harbor地址，普通用户没有同步账号按钮
![](https://github.com/user-attachments/assets/bfd8333b-6f66-49ce-ae81-de97c32622e0)

**Comment by dingluyy** [comment]
- [x] 33. 管理员账号，创建仓库项目，设置项目容量设置100MiB，保存后是100GiB，单位保存错误
- [x] 34. 非管理员权限，创建仓库项目，不应该有项目容量设置，因为配置了保存也不生效
- [x] 35. 没有仓库项目角色/仓库项目受限访客角色，镜像仓库概要页不应该展示成员角色部分
- [x] 36. harbor v1版本，配置Harbor 时版本选择v2，提示信息需优化
- [x] 37. 标签页（Harbor配置页标签部分/镜像仓库标签页）的操作按钮edit和delete没有翻译
![](https://github.com/user-attachments/assets/f2d26254-0632-4c96-8a1a-e6a8ff1d8344)

- [x] 38. Artifacts列表页，点击复制摘要，没有复制成功
- [x] 39. 创建仓库项目，不输入名称，提示两个错误提示，保留 ‘请输入项目’ 就行
- [x] 40. 删除包含镜像的镜像仓库，镜像仓库删除失败，没有错误提示
- [x] 41. 新建标签，标签130个字符，有两个提示
- [x] 42. 普通用户登录rancher，创建仓库项目时，不应展示 存储容量，保存不生效。
- [x] 43. 普通用户登录rancher，不是仓库项目的成员，选择一条仓库项目，点击删除。可以删除成功，删除按钮不应该可以点击跳转。
- [x] 44. 普通用户登录rancher，不是仓库项目的成员，概要页面，不应展示成员和存储容量，没权限；仓库项目受限访客，不应展示成员
- [x] 45. 普通用户登录rancher，不是仓库项目的成员/仓库成员角色为开发人员/访客/受限访客，进入项目仓库，点击镜像仓库，选择一条删除镜像仓库，可以点击成功，确认删除后，删除失败，一直加载页面
- [x] 46. 普通用户登录rancher，仓库项目成员角色为维护人员，点击仓库项目名称进入项目，点击镜像仓库，删除按钮被禁用。点击镜像名称，删除Artifacts，删除按钮被禁用。
- [x] 47. Harbor v1，镜像管理列表，搜索不存在的仓库项目，控制台爆粗，前端页面不展示
![](https://github.com/user-attachments/assets/f92ffafa-4211-4564-97b3-c659e2eca0d8)

- [x] 48. Harbor v1，镜像仓库管理，列表排序不生效
- [x] 49. Harbor v1，进入仓库项目，点击镜像仓库，列表Artifacts 字段没有值；点击镜像名称，Artifacts列表没有数据
- [x] 50. Harbor v1，日志列表，表头没有翻译
- [x] 51. Harbor v1，日志列表，除了按名称搜索其他搜索结果错误，查看接口，切换搜索类型，接口里类型没有变；没有分页，所有数据一起展示
- [x] 51. Harbor v1，进入仓库项目，点击镜像仓库，输入存在的名称，搜索不到结果；选择镜像，删除失败，接口返回404
- [x] 52. Harbor v1，进入仓库项目，点击成员，分页数据不正确
![](https://github.com/user-attachments/assets/5d5f43fe-db92-44e4-9c3e-75108fbf36d2)
- [x] 53. Harbor v1，进入仓库项目，点击日志，镜像名称/资源类型 字段没有值
